services:
  oracle23ai:
    image: gvenzl/oracle-free:23.6-slim-faststart
    container_name: oracle23ai
    ports:
      - 1521:1521
    environment:
      - ORACLE_PASSWORD=Welcome12345
    volumes:
      - ./oracle:/container-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "lsnrctl status | grep READY" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
  sample:
    image: container-registry.oracle.com/database/godror-sample:latest
    container_name: sample
    environment:
      - DATABASE_CONNECTION_STRING=oracle23ai:1521/freepdb1
      - DATABASE_USERNAME=pdbadmin
      - DATABASE_PASSWORD=Welcome12345
      - QUERY_THREADS=100
      - USE_POOLING=true
    depends_on:
      oracle23ai:
        condition: service_healthy